return {
    ACTIONS = {
        CASTSPELL = {
            INSERT = "Insert",
            PULLOUT = "Pull Out",
            SUICIDE = "Suicide",
        },
        MDODGE = "Dodge",
    },
    CHARACTER_ABOUTME = {
        manutsawee = "Manutsawee is too long so just louis.",
    },
    CHARACTER_BIOS = {
        manutsawee = {
            {
                desc = "October 9",
                title = "Birthday",
            },
            {
                desc = "Learn Everything Technical College of Hawaii",
                title = "Current School",
            },
            {
                desc = "Unagi, Bacon and Eggs, Cooked Kelp Fronds, Durian, Roasted durian \nCaliforniaroll, Caviar \nSteamed Ham Sandwich, Tea, Ice Tea \nLiceloaf, Boomberry Pancakes",
                title = "Favorite Food",
            },
            {
                desc = "Manutsawee.",
                title = "Her Past...",
            },
            {
                desc = "A strange day and time in the plains, a city far away from the hustle and bustle, a journey to the countryside in the forest, and a shrine to see a shrine. In the shrine village where the shrine is destroyed, a bundle of offering clothing is covered with cloth and clothing. When the curiosity erupted, I touched the handle, and as a result I felt intense pain. When I understood the land, I was shocked and left the place. When they left, a single voice sounded. After the pain disappeared, the eyes turned red and turned red. The shrine has disappeared with no shadow...",
                title = "The origin of red eye",
            },
            {
                desc = "Tokijin\nThe cursed sword made from the fangs of the Ghost of God is full of evil, and ordinary people can easily be controlled by it.\nIt was originally broken by Sesshomaru, but Louis found it in an abandoned shrine.. .",
                title = "Cursed Sword",
            },
        },
    },
    CHARACTER_DESCRIPTIONS = {
        manutsawee = "*Art of the Japanese sword\n*Brave\n*Benevolent\n*Love to eat",
    },
    CHARACTER_NAMES = {
        manutsawee = "Manutsawee",
    },
    CHARACTER_QUOTES = {
        manutsawee = "\"Where There's a Will, There's a Way\"",
    },
    CHARACTER_SURVIVABILITY = {
        manutsawee = "󰀕Grim",
    },
    CHARACTER_TITLES = {
        manutsawee = "The Red-Eyes Girl",
    },
    M_LOADINGTIPS = {
        ABIGAIL_TENSEIGA = "\"I'm sorry, Tenseiga can't do anything to save her.\" - L",
        TOKIJIN = "\"I can't suppress its evil spirit, I can't control tokijin.\" - L",
        WANDA_REDEYES = "\"emmmm, that's weird, I can't see your past timeline, it's shrouded in a white mist.\" - W",
        WATHGRITHR_REDEYES = "\"Loki has given power to you!\" - W",
        WAXWELL_REDEYES = "\"I guess your eyes turned red, not from magic, but from a curse, a curse that doesn't belong here.\" - W",
        WEBBER_REDEYES = "\"Sorry, Miss Louis, I thought you were wearing red contact lenses\" - W",
        WICKERBOTTOM_REDEYES = "\"science can't explain why your eyes turn red, and neither can magic.\" - W",
        WILSON_REDEYES = "\"It doesn't matter, nothing is strange here, including this girl with red eyes.\" - W",
        WORTOX_REDEYES = "\"I guess you can see things that we can't see?\" - W",
    },
    NAMES = {
        BAKUSAIGA = "Bakusaiga",
        BOAT_MSURFBOARD = "Louis's Surf board",
        HARAKIRI = "Harakiri",
        HITOKIRI = "Nihiru",
        HMINGOT = "Hot Mysterious Ingot",
        KAGE = "Kage",
        KATANABLADE = "Katana Blade",
        KATANABODY = "Katana shape",
        KOSHIRAE = "Sakakura",
        MANUTSAWEE = "Manutsawee",
        MINGOT = "Mysterious Ingot",
        MMIKO_ARMOR = "Miko Robe",
        MORTALBLADE = "Mortal Blade",
        MSURFBOARD_ITEM = "louis's Surf board",
        M_PANTSU = "Blue and white striped pantsu",
        OINC1000000 = "Millionpiece Oinc",
        RAIKIRI = "Raikiri",
        SHINAI = "Shinai",
        SHIRASAYA = "Yasha",
        SHUSUI = "Shusui",
        TENSEIGA = "Tenseiga",
        TOKIJIN = "Tokijin",
        TRUE_HITOKIRI = "Nihiru The Bloodseeker",
        TRUE_KOSHIRAE = "Sakakura The Giant Slayers",
        TRUE_RAIKIRI = "Raikiri The Lightning Cutter",
        TRUE_SHIRASAYA = "Yasha The Demon Slayer",
        VSCODE = "Visual Studio Code",
        YARI = "Yari",
    },
    RECIPE_DESC = {
        HARAKIRI = "Pay your mistake.",
        HITOKIRI = "The Bloodseeker",
        KAGE = "Bring the shadows together.",
        KATANABLADE = "Sharp katana blade",
        KOSHIRAE = "The Giant Slayers",
        MINGOT = "Bring it to fire",
        MMIKO_ARMOR = "Miko robe for miko skin",
        MORTALBLADE = "To cut the immortality.",
        MSURFBOARD_ITEM = "louis's Surf board",
        RAIKIRI = "The Lightning Cutter",
        SHINAI = "Training Sword.",
        SHIRASAYA = "The Demon Slayer",
        SHUSUI = "A Legendary Sword of Wano.",
        TRUE_HITOKIRI = "True Nihiru",
        TRUE_KOSHIRAE = "True Sakakura",
        TRUE_RAIKIRI = "True Raikiri",
        TRUE_SHIRASAYA = "The Demon Slayer",
        VSCODE = "There is nothing that cannot be solved with one line of code.",
        YARI = "It's Japanese Spear.",
    },
    SKIN_DESCRIPTIONS = {
        lcane = "Would you believe a stick fell from the moon?",
        loading_dev_cemetery = "Players are still waiting for the update, while the authors have already gone to their graves.",
        loading_night_for_four = "A quiet and relaxing evening.",
        manutsawee_bocchi = "Goto Hitori's sportswear from Bocchi The Rock",
        manutsawee_fuka = "Fu hua hawk of the fog's outfit from honkai impact 3d",
        manutsawee_jinbei = "Japan's outfit.",
        manutsawee_lycoris = "Takina's outfit from Lycoris Recoil",
        manutsawee_maid = "Maid's outfit",
        manutsawee_miko = "Japan's shrine maiden outfit.",
        manutsawee_none = "Thai's school uniform",
        manutsawee_qipao = "China's dress",
        manutsawee_sailor = "Japan's school uniform",
        manutsawee_shinsengumi = "Laws of the Shinsengumi\nOne must not infringe the samurai code\nOne is not authorized to escape from office\nOne is not allowed to arbitrarily raise money\nOne must not arbitrarily handle litigations\nOne is not authorized to engage in personal conflicts\n",
        manutsawee_taohuu = "Vtuber: Taohuu's outfit",
        manutsawee_uniform_black = "Agent's uniform from Men in Black.",
        manutsawee_yukata = "Japan's outfit mini version.",
        manutsawee_yukatalong = "Japan's outfit.",
        mnaginata = "Naginata",
    },
    SKIN_NAMES = {
        lcane = "Moon cane",
        loading_dev_cemetery = "Mod abandoned (permanently unpatched)",
        loading_night_for_four = "Night for four",
        manutsawee_bocchi = "Guitar Hero",
        manutsawee_fuka = "Cosplay",
        manutsawee_jinbei = "Jinbei",
        manutsawee_lycoris = "Lycoris",
        manutsawee_maid = "Maid",
        manutsawee_miko = "Miko",
        manutsawee_none = "Louis",
        manutsawee_qipao = "Qipao",
        manutsawee_sailor = "Sailor Uniform",
        manutsawee_shinsengumi = "Shinsengumi",
        manutsawee_taohuu = "Taohuu",
        manutsawee_uniform_black = "MIB",
        manutsawee_yukata = "Kimono(M) ",
        manutsawee_yukatalong = "Kimono",
        mnaginata = "Naginata",
    },
    SKIN_QUOTES = {
        manutsawee_bocchi = "\"mu mu mu mu mu mu mu mu\"",
        manutsawee_fuka = "\"I'm a kung-fu master now.\"",
        manutsawee_jinbei = "\"Relax Feeling good.\"",
        manutsawee_lycoris = "\"Heart is running away! ! !\"",
        manutsawee_maid = "\"Guest sama, would you like a cup of coffee?\"",
        manutsawee_miko = "\"Can i fight with yokai?'\"",
        manutsawee_none = "I hate this uniform.",
        manutsawee_qipao = "\"Ni hao ..? Happy Lunar New Year!'\"",
        manutsawee_sailor = "\"So so so... nothing just say so..\"",
        manutsawee_shinsengumi = "\"One must not infringe the samurai code!\"",
        manutsawee_taohuu = "\"I'm cute, please give me money.\"",
        manutsawee_uniform_black = "\"It's because the light from Venus is reflected on...the swamp gas...so...\"",
        manutsawee_yukata = "\"Shine omae! haha.'\"",
        manutsawee_yukatalong = "\"Kon ni chi wa ..?'\"",
    },
    UI = {
        WORLDGEN = {
            M_NOUNS = {
                "Louis's pantsu...",
                "Takina's pistol...",
                "Kiritzuka's sushi...",
            },
            PL_NOUNS = {
                "Millionpiece Oinc",
            },
        },
    },
}
