return {
    DESCRIBE = {
        BOAT_MSURFBOARD = "Very exquisite workmanship.",
        HARAKIRI = "This knife look so good.",
        HITOKIRI = "What a weird sword.",
        HMINGOT = "it's very hot!",
        KAGE = "",
        KATANABLADE = "Is it can use without sword-handle?",
        KATANABODY = "so what?",
        KOSHIRAE = "What a beautyful sword.",
        MAID_HB = "It's look good.",
        MINGOT = "What is this?",
        MMIKO_ARMOR = "Not for me.",
        MORTALBLADE = "To cut the immortality.",
        MSURFBOARD_ITEM = "Which lady's surfboard is this?",
        M_FOXMASK = "What a nice mask!.",
        M_PANTSU = "..?",
        M_SCARF = "It'll be good for when winter comes.",
        OINC1000000 = "我的无畏舰在哪里？",
        RAIKIRI = "What a beautyful sword.",
        SHINAI = "Is this useful?",
        SHIRASAYA = "What a beautyful sword.",
        SHUSUI = "It's beautiful.",
        TENSEIGA = "On its blade, there is no sharpness or killing intent.",
        TOKIJIN = "Demonic spirit?",
        TRUE_HITOKIRI = "What a weird sword.",
        TRUE_KOSHIRAE = "What a beautyful sword.",
        TRUE_RAIKIRI = "This sword look dangerous,Don't touch it.",
        TRUE_SHIRASAYA = "What a beautyful sword.",
        VSCODE = "Tools from another world.",
        YARI = "This spear look different.",
    },
}
